"""consolidated_models

Revision ID: 6992ff4f4369
Revises: 
Create Date: 2025-07-28 13:57:44.198817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6992ff4f4369'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('skills', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('users', sa.Column('resume_status', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('training_status', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('admin', 'consultant', name='userrole'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.drop_index(op.f('ix_users_name'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=True)
    op.alter_column('users', 'role',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('admin', 'consultant', name='userrole'),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'training_status')
    op.drop_column('users', 'resume_status')
    op.drop_column('users', 'skills')
    # ### end Alembic commands ###
