"""Add resume_file to user

Revision ID: 776a66df0c4f
Revises: d9857d9a2d5e
Create Date: 2025-08-04 08:21:26.122311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '776a66df0c4f'
down_revision: Union[str, Sequence[str], None] = 'd9857d9a2d5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('resume_file', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'resume_file')
    # ### end Alembic commands ###
