"""Add completed trainings table

Revision ID: e0b489a19e08
Revises: 0e7158b12927
Create Date: 2025-08-06 19:22:07.292694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0b489a19e08'
down_revision: Union[str, Sequence[str], None] = '0e7158b12927'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('completed_trainings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consultant_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('completed_date', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['consultant_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_completed_trainings_id'), 'completed_trainings', ['id'], unique=False)
    op.create_table('training_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('skill', sa.String(), nullable=True),
    sa.Column('course_title', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_recommendations')
    op.drop_index(op.f('ix_completed_trainings_id'), table_name='completed_trainings')
    op.drop_table('completed_trainings')
    # ### end Alembic commands ###
